/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendorsRouteImport } from './routes/app.vendors'
import { Route as AppVehiclesRouteImport } from './routes/app.vehicles'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRoutesRouteImport } from './routes/app.routes'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQrcodesRouteImport } from './routes/app.qrcodes'
import { Route as AppPickupsRouteImport } from './routes/app.pickups'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppKycRouteImport } from './routes/app.kyc'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppCollectionsRouteImport } from './routes/app.collections'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQrcodesRoute = AppQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AppRoute,
} as any)
const AppPickupsRoute = AppPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppKycRoute = AppKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/collections': typeof AppCollectionsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/kyc': typeof AppKycRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/pickups': typeof AppPickupsRoute
  '/app/qrcodes': typeof AppQrcodesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/routes': typeof AppRoutesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/app/vendors': typeof AppVendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/collections': typeof AppCollectionsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/kyc': typeof AppKycRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/pickups': typeof AppPickupsRoute
  '/app/qrcodes': typeof AppQrcodesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/routes': typeof AppRoutesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/app/vendors': typeof AppVendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/collections': typeof AppCollectionsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/kyc': typeof AppKycRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/pickups': typeof AppPickupsRoute
  '/app/qrcodes': typeof AppQrcodesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/routes': typeof AppRoutesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/app/vendors': typeof AppVendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/collections'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/kyc'
    | '/app/notifications'
    | '/app/payments'
    | '/app/pickups'
    | '/app/qrcodes'
    | '/app/reports'
    | '/app/routes'
    | '/app/settings'
    | '/app/users'
    | '/app/vehicles'
    | '/app/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/collections'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/kyc'
    | '/app/notifications'
    | '/app/payments'
    | '/app/pickups'
    | '/app/qrcodes'
    | '/app/reports'
    | '/app/routes'
    | '/app/settings'
    | '/app/users'
    | '/app/vehicles'
    | '/app/vendors'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/collections'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/kyc'
    | '/app/notifications'
    | '/app/payments'
    | '/app/pickups'
    | '/app/qrcodes'
    | '/app/reports'
    | '/app/routes'
    | '/app/settings'
    | '/app/users'
    | '/app/vehicles'
    | '/app/vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vehicles': {
      id: '/app/vehicles'
      path: '/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/routes': {
      id: '/app/routes'
      path: '/routes'
      fullPath: '/app/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qrcodes': {
      id: '/app/qrcodes'
      path: '/qrcodes'
      fullPath: '/app/qrcodes'
      preLoaderRoute: typeof AppQrcodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pickups': {
      id: '/app/pickups'
      path: '/pickups'
      fullPath: '/app/pickups'
      preLoaderRoute: typeof AppPickupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kyc': {
      id: '/app/kyc'
      path: '/kyc'
      fullPath: '/app/kyc'
      preLoaderRoute: typeof AppKycRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections': {
      id: '/app/collections'
      path: '/collections'
      fullPath: '/app/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppKycRoute: typeof AppKycRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPickupsRoute: typeof AppPickupsRoute
  AppQrcodesRoute: typeof AppQrcodesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoutesRoute: typeof AppRoutesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppVendorsRoute: typeof AppVendorsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCollectionsRoute: AppCollectionsRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppKycRoute: AppKycRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPickupsRoute: AppPickupsRoute,
  AppQrcodesRoute: AppQrcodesRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoutesRoute: AppRoutesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppVendorsRoute: AppVendorsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
